### ISSUE TITLE
Update Binary + Infos

### ISSUE THREAD

**Issue by donovan0** [ron190/jsql-injection#1]
Hello,

I follow your app, since you launch it i think,( from google rep..) i am on OSX, & your GUI App is propably the only one on OSX, so thank you for that.

Since you launch the V6, i make a lot of test & i need to talk to you about, can you please contact me in private.

Beside, i just sse you update the app 21 days a go, have you planed to update also the Binary here = https://github.com/ron190/jsql-injection/releases  ( this one is dated from Jan 2 ) ?

Thank you in advance,

Regards,

Don

**Comment by ron190** [comment]
Hi,

I don't know how your issue was hidden from me for so long, my bad. Thank you for your interest on v0.6 on OSX.

Yes, the binary release process is currently not in sync with the source updates, I usually release .jar when significant changes are made. However I document myself on continuous delivery and I hope I will release binaries automatically as fast as code is commited.

You can of course contact me by mail on my ymail address.
Rgds

**Comment by donovan0** [comment]
Hi Ron',

Thank you for your reply & don't worries about delay, it's ok...

Ok understand for the binary, no problem, i will wait the next update...

Concern my test's i do with JSQL on OSX , yes i will contact you then by
e.mail , can you please recall me your adress i do not find it

Regards,

Don'

2015-04-10 22:42 GMT+02:00 ron190 <notifications@github.com>:

**Comment by ron190** [comment]
You can find my mail adress in the menu 'Help' / 'About' in jSQL (press command key to display menubar in alpha.v0.6), or in this source file on Github : 
https://github.com/ron190/jsql-injection/blob/master/src/com/jsql/view/swing/dialog/about.htm#L32

**Comment by donovan0** [comment]
Ok, got it, thank you, i will write you ASAP then ;-)

2015-04-11 3:18 GMT+02:00 ron190 <notifications@github.com>:
