### ISSUE TITLE
Proxy error on windows

### ISSUE THREAD

**Issue by sharma14skss** [ron190/jsql-injection#3]
hi,

i connect proxy through Tor browser but getting error when connect network

when ip check : Error during AWS proxy test: Server returned HTTP response code: 501 for URL: http://checkip.amazonaws.com
Error during Telize proxy test: Server returned HTTP response code: 501 for URL: http://www.telize.com/geoip

when connect websites : Connection problem: Server returned HTTP response code: 501 for URL:

checked version : v0.4 ,v0.5 and v0.6 alpha 
os: windows8
![1](https://cloud.githubusercontent.com/assets/9606647/8593116/7274f4a6-2652-11e5-8dbb-f6fc24de73e9.png)

**Comment by ron190** [comment]
I usually use port 8118 with TOR, can you test this port instead of 9150 ?
This thread from the forum gives some hints:
https://groups.google.com/forum/#!topic/jsql-injection/fT5nVbQnVpI

**Comment by ron190** [comment]
There's must be some change on TOR protocol, I get the same issue ; I'll figure out what's going on and report from here there.

**Comment by ron190** [comment]
I usually typed Proxy port 8118 in jSQL but this port seems no more available directly to access TOR ; we need to use Privoxy in addition to TOR in order to use 8118 in jSQL.

Start TOR, then download the zip for Privoxy, click Edit / Main Configuration in Privoxy and add this line to the file config.txt :
```
forward-socks5 / 127.0.0.1:9050 .
```
Save your config.txt and restart Privoxy, it will now listen to port 8118 and forward communication to TOR : use port 8118 in jSQL and it should work as expected.

**Comment by catgames** [comment]
yeah its work ....
but i change that code  
forward-socks5 / 127.0.0.1:9050 .     to 
forward-socks5 / 127.0.0.1:9150 .  
because my working tor port is 9150...
thanks ron190.. and add more payloads for bypass mod security because sometimes not able to bypass that in jsql.... but sqlmap can do if we add some tamper scripts .... good luck  
![2](https://cloud.githubusercontent.com/assets/9606647/8612666/ebdcb08c-26f1-11e5-8825-942e776f9991.png)

**Comment by BosSLtd** [comment]
hi,

only http proxy? https does not work?

**Comment by ron190** [comment]
You are right @BosSLtd, actually jSQL uses properties `http.proxyHost` and `http.proxyPort`. Properties `https.proxyHost` and `https.proxyPort` are currently unused.

I will give user the possibility to set both http and https in the next release.
Thank you for the report.

**Comment by BosSLtd** [comment]
Thanks for your work!
