### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by lzskyline** [ron190/jsql-injection#50211]
First at all, thanks for you developing this project.
I found jSql has a connection test before it starts trying to injection test the url, it's a smart way to decide if injection test needs to go on.However, some WAF will return code 500 if you do not post a special value. That will make jSql work incorrectly, so I think you may let the user choose whether it needs to continue or not. :)

**Comment by ron190** [comment]
You are welcome, I guess you are referring about CSRF token.

First the user makes a call to get a token which is returned inside a HTML form, cookie or header, then he add this token to further calls through URL, POST or header in order to get accepted by the website, otherwise he gets an error like error code 500.
Tell me if I'm completely wrong and you think about an entirely different process.

I haven't worked on CRSF yet, but I think I can add a convenient way to let the user define the token name in the Advanced panel.

**Comment by lzskyline** [comment]
I think that is not limited to CSRF, but the principle is similar.
For example:
In the login.html page. There are such a form in HTML
<FORM ACTION = "check.php" />
And in check.php, first, check whether is POST request, the second, check whether there is a field named username. Any one that not pass the check will return error code 500, rather than the success code 200.
Actually, I'm often using this way to aviod malicious attacks.

**Comment by ron190** [comment]
Are you thinking about an option `Ignore connection failure (y/n)` ?

Otherwise for the specific case you described about missing fields, actually the user receives a nasty technical message during the connection test:
`[23:19:34,658] Connection failed: java.io.IOException: Server returned HTTP response code: 500 for URL: http://127.0.0.1/simulate_get.php?lib=0`

I could improve the text and add advises about WAF and missing parameters to help the user find what is the problem, but I suppose he can't really choose to continue without finding the missing field first.

Anyway if failure occurs then jSQL could parse the test page to find `<input>` tags and display them to the user, there's a chance the missing field is in the list (tricky though because not guaranteed and must be done after the redirection).

Note on CSRF: I suppose the token could be retrieved from HTML/Header and injected into URL/POST/Header nearly automatically based on a list of predefined token names. Also user could define his own token in Advanced Settings.

**Comment by lzskyline** [comment]
To ask user whether he want to ignore failure might be some abrupt, because the current detection is fully automatic.
So I thought about another way to solve this problem.
About fields missing, maybe you can add a feature just like --forms" in SQLMAP, let jSQL finding the parameters in the form in a given URL automatically, such as:
[checkbox]Automatically load FORM (?: You can input a URL that contains forms, jSQL will try to use the first form in page, and check those parameters if have injections. All parameters will be checked in turn. )

Another though to check if jSQL needs go on, you may check to error code 404 instead of 500, surely, if a URL return error code 500, the test will still stop if the user doesn't choose the checkbox: "Don't test the connection (?: Force injection test without connection test)" or "Bypass WAF" (may inappropriate before you develop other bypass way in jSQL).

How do you like this? :)

**Comment by ron190** [comment]
I like it already ;)

I will plan to add a new option to parse and load `<form>` params automatically, i.e:
- `[*] Parse and load <form> parameters`

Still, the case you described earlier with `login.php` redirecting to `check.php` will be tricky to process because when redirecting Java does not give access to the source of `login.php`. Though I guess parsing params from `login.php` can be done before redirecting manually to `check.php`.

Also currently jSQL tests only for the last parameter of the method selected by the user (URL, Request or Header). I think I'll add another option to check for other parameters too, i.e:
- `[-] Check all parameters for injection`
    - `[*] Check all URL parameters`
    - `[ ] Check all Request parameters`
    - `[*] Check all Header parameters`
- `[*] Check JSON parameters for injection`

Finally, the connection test catches any HTTP Exception, 500, 401, 404... it's not limited to a specific error, but I think that reducing the range of errors could be efficient too. In all cases it can be useful to add an option to disable the test, i.e:
- `[*] Test the connection before processing to the injection`

**Comment by lzskyline** [comment]
wonderful, thanks for your good job :)
I'm sorry for not being able to help develop. I hope that jSQL will be as famous as sqlmap

**Comment by ron190** [comment]
Thanks to you, translating text and giving ideas like you did is a lot of help, no worries.

Programming is only one part of any project like jSQL, a lot can be done outside programming skills. 

Here is a list of things that are really helpful to do for anyone who wants to contribute, ordered by easiness:
1. Download and have fun with jSQL,
1. Spread the word to friends and others, do a blog post, a tweet, a video about jSQL,
2. Contact me on Twitter/Youtube/Mail, give a star or fork on Github, subscribe to Twitter account,
1. Use jSQL and report bugs, Translate some text and button, Write documentation,
1. Participate and give advices on new features and [planned programming](https://github.com/ron190/jsql-injection/projects),
1. Help optimize injection algorithms and SQL queries,
1. Push code on Github.

_I'll leave this thread open until the features are implemented._

**Comment by ron190** [comment]
I've just released version [v0.80](https://github.com/ron190/jsql-injection/releases/download/v0.80/jsql-injection-v0.80.jar), I think it covers nearly all the subjects we have discussed here, except from Tampering.
