### ISSUE TITLE
[community]Any future port to Android?

### ISSUE THREAD

**Issue by SciFi1818** [ron190/jsql-injection#68989]
Now jsql supports every major os except Android..

It's a bit difficult for now to port the ui..

But can we hope an Android edition in the coming months??

**Comment by ron190** [comment]
Good point.

Portability is provided by the JVM itself. Each program packaged as a .jar can be run on either Windows/Linux/Mac, that's why I have chosen Java in the first place.

Now running a .jar directly on Android is not possible but emulators [can actually do it](https://softwarerecs.stackexchange.com/a/13860). I'm curious to know if it runs smoothly though.

**Comment by SciFi1818** [comment]
Unfortunately, it is not the regular j2se emulator, they are j2me emulator.

**Comment by ron190** [comment]
I don't know the Android platform very well, but I think MVC pattern of jSQL makes its Model reusable with completely another View, like anything lighter than Swing, for example like Command Line Interface, or even JavaFX.

Currently there's no Web API implemention to control jSQL from any kind of platforms and applications, so we are to use Swing for now, but I think even Burp currently keeps Swing as its main GUI.

Nevertheless if I or a contributor creates a View compatible with Android or compatible with j2me emulator then it should work just by reusing the Model. I have just added [the corresponding task](https://github.com/ron190/jsql-injection/projects/1#card-8561368) to the project for anyone who wants to contribute.

**Comment by ron190** [comment]
Pentesting from Android seems strange to me actually.
