### ISSUE TITLE
when i upload file the exception oc

### ISSUE THREAD

**Issue by irunmyway** [ron190/jsql-injection#90382]
Payload creation error: com.jsql.model.exception.JSqlException: Payload integrity verification failed: 锘夸腑缁у櫒 A<br>璁＄畻鏈�璁＄畻鏈虹綉缁�A<br>缃戞ˉ C<br>鍒嗙粍浜ゆ崲鎶�湳 A<br>鐗╃悊灞傚拰閾捐矾灞�D<br>绗琋 灞備负绗琋+1 灞傛彁渚涙湇鍔°� A<br>www.nk.cn.edu B<br>涓�釜VLAN缁勬垚涓�釜骞挎挱鍩�A<br>鍏夌氦 D<br>MAC鍦板潃鍏ㄧ悆鍞竴 A<br>閫氫俊鎶�湳 B<br>璁＄畻鏈烘妧鏈笌閫氫俊鎶�湳 B<br>鍙 C<br>浼犺緭灞�D<br>浼犺緭灞�D<br>鎷掔粷鏈嶅姟鏀诲嚮 A<br>閫氫俊鎶�湳 B<br>鎻愰珮绾胯矾璐ㄩ噺 A<br>璁＄畻鏈烘妧鏈笌閫氫俊鎶�湳 B<br>32浣�C<br>1 <br>

**Comment by ron190** [comment]
The error happens when the PHP payload that uploads file is different than the one injected by SQL injection.

First verify that you have `FILE privilege` activated and that the server is running PHP.

Then try to read the payload directly from the server using the tab `Read file`. The name of the upload payload is usually `.v0.81.ju.php`.

**Comment by irunmyway** [comment]
i can see datebase stucture and i hava file privilege ,i am sure it activated but i can‘t get any file or upload any file ,look this picture
<img width="308" alt="1" src="https://user-images.githubusercontent.com/33797433/71317657-ad1e0280-24bf-11ea-9df1-dedecfbae186.png">
<img width="336" alt="2" src="https://user-images.githubusercontent.com/33797433/71317659-b1e2b680-24bf-11ea-9372-8004ed5821e1.png">

**Comment by ron190** [comment]
You can try to select the whole list in tab `File` and click on `Read file(s)` to test that at least one file can be read by SQL. You may need Full Path Disclosure to know the correct path of the file on the server.

If there's zero file to read then consider it done, because writing a payload is not easier.

Or you'll need to debug the HTTP and SQL requests manually to understand what is blocking on the backend and what is incorrect:
- Is it the payload path?
- Is it the payload content?
- Is it the SQL query?
- Is it the URL?

Use the `Network` tab to get the URL and query and try to update the requests manually.

**Comment by irunmyway** [comment]
thank u bro, i can already fond 3file on 79 files checked,but its path not www path,i want to upload file to its www path so that i can use eval commande .how can i get its www path,any better ways? or i  can only guess?

**Comment by ron190** [comment]
Ok, it means SQL manages to read source code directly from the server.

If the file is `.php` or `.htm` in folder `/var/www/` then you found a Web folder on the server, and the files in that folder can be accessed by an HTTP URL. In that case Web shell, SQL shell and Upload may work.

If you have not found a Web folder then you need Full Path Disclosure tools or guessing, or also try a query like `http://site.com/index.php?page[]=about` to get an error message from the server that contains the path of Web folder, like I describe when you hover `Read file(s)`:

<img width="400" alt="2" src="https://user-images.githubusercontent.com/1971480/71323593-33910f00-24d5-11ea-868b-776b7566c72d.png">
