### ISSUE TITLE
Virus Total say it have adware virus

### ISSUE THREAD

**Issue by hakdogpinas** [ron190/jsql-injection#94244]
The latest version detected that the .jar files is having an adware.

https://www.virustotal.com/gui/file/c605e7e8ce1d87cb4de718304b2b4a7bf7d1426949a359cd870d9512e4136f23/detection

can you clarify this?

**Comment by ron190** [comment]
Sure, 

- First, upload v0.76 to virustotal, see that it found no threat whereas v0.76 already integrates a [PHP shell feature](https://github.com/ron190/jsql-injection/blob/v0.76/src/main/java/com/jsql/model/accessible/RessourceAccess.java#L192) like other popular tools do

- Then upload v0.77, confirm there's a PHP threat because it was already there in v0.76 `¯\_(ツ)_/¯`

- Continue to upload v0.83, see that another threat not related to PHP is found, while the PHP shell is still [there](https://github.com/ron190/jsql-injection/blob/v0.83/model/src/main/resources/config.properties#L26).

And from here stop wondering what online scanners report because it's not reliable and people just have the source code before their eyes in any doubt.

So, base your opinion on trust and do not use tool not trusted by the community.

A task is added to [the project board](https://github.com/ron190/jsql-injection/projects/1#card-53703048) to obfuscate shells like other tools do, thanks for your feedback!

> Additional resources
> - Obfuscated shells in [other tool](https://github.com/sqlmapproject/sqlmap/tree/master/data/shell) with explanation
> - Scan report of [Metasploit](https://github.com/rapid7/metasploit-framework), to be clarified (not)
> <img src="https://user-images.githubusercontent.com/1971480/106063303-3f97c900-60f8-11eb-82cc-109d2d17e4b3.png" width="300">
