### ISSUE TITLE
strategy locked

### ISSUE THREAD

**Issue by hastalamuerte** [ron190/jsql-injection#95344]
Cant set strategy from start of scanning.. Why? plz add that function.

**Comment by ron190** [comment]
Yes, because the tool tests automatically all the strategies that exist first, then it enables the strategies that are confirmed.
Currently what is considered is that the user shouldn't waste time on any strategy that is not confirmed by the tool.

Imagine you would choose `Normal` while that strategy is absolutely not available on the target. 

Though I get that when you absolutely know that `Normal` is available you would want to use directly that strategy without testing the other ones.

### Available strategies vs Unconfirmed strategies (grayed choices):
<img src=https://github.com/ron190/jsql-injection/raw/master/web/images/v0.75/database.png width=480 />

**Comment by hastalamuerte** [comment]
> Yes, because the tool tests automatically all the strategies that exist first, then it enables the strategies that are confirmed. Currently what is considered is that the user shouldn't waste time on any strategy that is not confirmed by the tool.
> 
> Imagine you would choose `Normal` while that strategy is absolutely not available on the target.
> 
> Though I get that when you absolutely know that `Normal` is available you would want to use directly that strategy without testing the other ones.
> ### Available strategies vs Unconfirmed strategies (grayed choices):
> 
> <img alt="" width="480" src="https://github.com/ron190/jsql-injection/raw/master/web/images/v0.75/database.png">

plz unlock . In nearby issue i describe the situation, and only your soft can how i see now exploit that sqli. I was made ALLL with sqlmap - nope. There is a lot of troubles with WAF, cookie , number of requests and etc. 

Guys, i believe in you

**Comment by ron190** [comment]
> But! i need to reduce requests.

You can reduce traffic using the option `Limit processing threads`, also you may enable some options in tab `Injection` if only the strategy `ErrorBased` is required.
### Option Limit threads
<img src=https://user-images.githubusercontent.com/1971480/173195194-4cc67d12-4ebc-48d3-a1fa-23d62472bcf3.png width=480>

### Option unused for strategy `ErrorBased`
<img src=https://user-images.githubusercontent.com/1971480/173195242-802c790c-b9a0-400e-a670-4a0720e1c6de.png width=480>
