### ISSUE TITLE
Fetching fails: no data to parse  error

### ISSUE THREAD

**Issue by ErrorMySQL** [ron190/jsql-injection#95454]
i have problem "Fetching fails: no data to parse " whene i dump big data

any sollution?

![jsql injection problem](https://github.com/ron190/jsql-injection/assets/89150273/8fc28e3a-44da-4786-b9ce-c2157c14cecf)

**Comment by ron190** [comment]
You correctly get names for databases, tables and columns it appears, so possibly:

- the query for rows is incorrect
- the backend is protected by waf

Look at tab Network for more details on the query, the HTTP response code, the source page, the metadata, and any other root cause. You should try to test and fix the query in your browser manually, then access tab SQL Engine to adapt the query for rows.

Also share any non-confidential data that could help, as the database type, the injection strategy, jSQL version, root cause analysis and so on.
