### ISSUE TITLE
Disable url encode is not working

### ISSUE THREAD

**Issue by mastercho** [ron190/jsql-injection#95493]
## What's the expected behavior?
When i click Disable URL encoding from preferences to not encode URL, and when i delete the end comment to not put in end comment in testing

## What's the actual behavior?
Encodes URL and adds ending comment when i delete it
![image](https://github.com/ron190/jsql-injection/assets/1971480/f72236fb-07c0-4a92-a725-c8a5150c9c4a)

## Any other detailed information about the Issue?
payload is as follows site.com/load/if(now()=sysdate(),sleep(6),0)
or can be any other sleep query like in Ghauri
![image](https://github.com/ron190/jsql-injection/assets/1971480/daf64e80-0d76-4b8f-818a-e72f73df6cc1)

## Steps to reproduce the problem

  1. Disable URL encoding from preferences
  2.  Remove ending comment from SQL Engine
  3. Run scan

**Comment by ron190** [comment]
@mastercho New release [v0.93](https://github.com/ron190/jsql-injection/releases/tag/v0.93) includes:
- a new Preference to disable the random URL suffix
- a fix for empty value not set in SQL Engine

You should be able to combine the star injection point `*`, disable Preference `URL suffix` and remove the SQL Engine `End comment` for similar advanced use cases.

Ideally jSQL should search for that injection automatically without any manual settings but it looks like an advanced use case.

**[Screenshot] Strategy Time validated with `URL suffix` enabled and `End comment` removed:**

![image](https://github.com/ron190/jsql-injection/assets/1971480/18bb6c2c-b879-40f7-b21a-79d2019b4321)

**Comment by ron190** [comment]
`URL suffix` and `Ending comment` are the root cause I guess, `URL encoding` should not be a problem usually.

**Comment by mastercho** [comment]
@ron190 thanks for fixing 

- random URL suffix
- empty value not set in SQL Engine

But for my cases disable of URL encoding really needed because if(now()=sysdate(),sleep(6),0) payload 90% of cases always fails on urlencode and its still not fixed, and even i Disable URL encoding (above of new option in preferences) still encode URL in requests, also what i notice is adds space as prefix, cant find where to take out this?

**Comment by ron190** [comment]
> if(now()=sysdate(),sleep(6),0) payload 90% of cases always fails on urlencode

There shouldn't be any direct correlation between URL encoding and SQL failure.
URL encoding should not matter in most cases, also disabling URL encoding looks mostly fine on my side (see screenshots, note: some special URL chars like `&`, `#` or `space` will always be encoded).

Also in some rare situation the server can limit the URL size (see JuiceShop example). In that case it's a problem of URL size, and you can enable Preference `Use Zip mode` to get a URL size divided by 2.

You may validate and track the root cause manually in your browser in order to know exactly what's failing. Defining the manual queries that fail and the related queries that pass can provide tips about the precise root cause.

**[Screenshot] Preference `Use Zip mode` enabled with `URL encoding` disabled to reduce size of URL:**
<img src=https://github.com/ron190/jsql-injection/assets/1971480/3d61eb8a-c07a-4fe1-8fcb-bc16e6960109 width=640 />
**[Screenshot] Default URL size with `URL encoding` disabled:**
<img src=https://github.com/ron190/jsql-injection/assets/1971480/4f6df4ae-7cae-46b6-b665-5ae277d1b224 width=640 />

**Comment by mastercho** [comment]
@ron190 i know chars like `&`, `#` or `space ` will always be encoded also i know the case with JuiceShop, but this nothing is relevant to my question: It's still encoded URL on me even i disable it...
![AnyDesk_0eOpZliC5t](https://github.com/ron190/jsql-injection/assets/10222100/4fcb58f0-88ba-48c3-92f9-2587c2de41ff)
![AnyDesk_gIceZWWSWb](https://github.com/ron190/jsql-injection/assets/10222100/ce33cfb1-007d-4cdb-90c2-e82c5ad4ce6b)

And you didn't explain why always adds space on my URL as prefix, is because of `/` ?

I verified in BURP and in Browser that URL Encode is the cause payload to failed and its important to not encode the URL.

**Comment by ron190** [comment]
@mastercho Problem is coming from the path injection which is a different use case.
New release [v0.94](https://github.com/ron190/jsql-injection/releases/tag/v0.94) disables encoding also during path injection and for most applicable chars (see screenshot).
I'm not sure about the prefix %20, I'll look into it if I can reproduce.

![image](https://github.com/ron190/jsql-injection/assets/1971480/7dd58070-84ad-4a32-931f-4cd2950d1650)

**Comment by mastercho** [comment]
let me know if you find anything about prefix %20 or maybe we should move this to new issue ticket @ron190

**Comment by ron190** [comment]
@mastercho I'm working on it, we can continue on this thread.

### Note on `%20`
The prefix `%20` was forced to avoid incorrect query `...1union...` when param like `1` is validated.

The space was covering both use cases:
- quoted param `...' union...` 
- integer param `...1 union...`

And I'm currently adapting the code to get a better result:
- quoted param `...'union...` (no space)

Also it seems that your use case with path param and star `*` was not requiring any `'` or `1`, which is lucky but leads to the following fix. 

### Star `*` behavior

Another fix is required because currently the param `'` or `1` won't be found automatically with `*` in `...&injecMe=*`, the user needs to set it manually which is not what is expected I guess:
- quoted param `...&injecMe='*`
- integer param `...&injecMe=1*`

**Comment by ron190** [comment]
@mastercho New release [v0.95](https://github.com/ron190/jsql-injection/releases/tag/v0.95) should produce SQL query with required characters only (hopefully :crossed_fingers:).
