### ISSUE TITLE
Strategy problem

### ISSUE THREAD

**Issue by konn-neko** [ron190/jsql-injection#95490]
## What's the expected behavior?
when swaping stats after some are found but one errors, you swap it to another to try it and it works
## What's the actual behavior?
swaping then running again resets strat to auto
## Steps to reproduce the problem

  1. scan site vuln to few strats
  2. let it error
  3. change strat
  4. run again
  5.

**Comment by ron190** [comment]
### Issue
@konn-neko Restarting the injection is resetting strategies because the strategies require to be validated by the tool.
The user should not be able to select a strat that has not been initially validated by the tool.

Though you can disable any useless strats in Preferences (see last screenshot).

But I would need more details to understand exactly your issue:
> 1. scan site vuln to few strats :point_left: Can you describe?
> 2. let it error  :point_left: Can you describe?
> 3. change strat :point_left: Can you describe?

### Note
Here's what the tool is doing as a reminder:

- All strats are disabled by default:

<img src=https://github.com/ron190/jsql-injection/assets/1971480/0145b02c-ccc8-4b8f-b9b0-670fc5b7a15a width=480 />

- A strat is automatically enabled and checked when validated by the tool (here all strats are succesful except for Multibit and Stacked):

<img src=https://github.com/ron190/jsql-injection/assets/1971480/15dffb71-6d74-4ba2-a890-06bc0145fdd7 width=640 />

- Then I can switch manually to another strategy (here from **Normal** to **Error**):

<img src=https://github.com/ron190/jsql-injection/assets/1971480/a01426cd-d511-43ec-b597-abdf3dbc7ecc width=640 />

- I can also disable strats that I do not want to test nor to use:

<img src=https://github.com/ron190/jsql-injection/assets/1971480/ee90c447-9994-40f5-a428-b85ff22d3621 width=480 />

**Comment by konn-neko** [comment]
Thank for the this, I thought it was bug when it's intentional. Have a great day
