### ISSUE TITLE
How to run the Jsql Injection with account using email and password inside site vulnerable with SQL injection

### ISSUE THREAD

**Issue by ErrorMySQL** [ron190/jsql-injection#95500]
### **i use cookie and authentication with email+pass but not working**

**this post vurnable must be use email and pass for working**

**how to exploit it?**

```
POST /fr/secure/download.delib HTTP/1.1
Host: www.target.com
Cookie: _ga=GA1.2.1665357407.874389515; _ga_7ZFYXK2LRP=GS1.2.169123459.5.1.1655546633.0.0.0; education_email=test@gmail.com; education_pass=***********; education_salt=1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Te: trailers
Connection: close
Content-Type: application/x-www-form-urlencoded
Content-Length: 44

id=111111&key=111111

```
![2](https://github.com/ron190/jsql-injection/assets/89150273/9e036d78-9fab-4159-b9c4-73eb58dffc83)

**Comment by ron190** [comment]
> i use cookie and authentication with email+pass

@ErrorMySQL Here are simple trivia steps, but you may have tried already:

1. [In browser] Log to the website with your browser using mail/password
2. [In browser] Get the `cookie` header values from the browser (key `F12`)
3. [In jSQL] Paste URL in jSQL
4. Paste parameters in request POST
5. Paste cookie parameters in Header
6. [End] It should work automatically if POST parameter `key` is injectable
7. Else if `id` is injectable then choose:
    1. Either paste POST parameters as `key=111111&id=111111` as last param is injected by default
    2. Or select Preference `Inject each Request parameter` to test both params
    3. Or paste POST params with star `*` injection point like `id=*&key=111111`

Also check for the logs in tab `Network|Réseau` and look at the website's responses in search for any clue related to the root cause.

Do not use `Basic` authentication except if your browser opens a prompt window like the following:

<img src=https://github.com/ron190/jsql-injection/assets/1971480/669f0821-9d12-4412-b116-b70352e336c5 width=480 />
