### ISSUE TITLE
Cookies set by host: ...

### ISSUE THREAD

**Issue by DelvinBa** [ron190/jsql-injection#95535]
![test](https://github.com/ron190/jsql-injection/assets/99075563/ef0a510c-6c98-4632-951a-64bdcc586b09)

So the problem is, that I am testing a testcase, where I know there is an sql injection. 
But the tool detects nothing. It is working in testcases, where I have to set no cookies.
But when there is a session cookie involved, it does not work. 
First the output says: "cookies set by host..." => here it changes the session cookie to an other value somehow.
Then: Found status HTTP 302 Redirection => I think it redirects to the login page, because the tool uses now an other session cookie(?).
After that it goes on with testing, but it detects nothing. So maybe I am setting the cookie wrong. The same setup works well with sqlmap, so I guess I am using the tool wrong.
Above is a picture of my request and the error. 
Also another question: How can I specify that for example only the parameter "title" gets tested. 

Thank you! I am comparing sqli tools in my bachelor thesis, and yours is one of them :)
I also wrote you a message on X, it would be nice if we can stay in touch, so that I can get the most out of your tool.

**Comment by ron190** [comment]
@DelvinBa I see that I've added endpoint `/bWAPP/sqli_1.php` to the scan list so it means I managed to inject the URL with jSQL.
And it should work until at least bWAPP challenge 17 according to my tests.

You should check the URL parameters consistency and the preferences options. 
So retry the test with:

- same cookie characters (last semicolon included)
- check that your cookie is correct and session is active (check calls and response in your browser)
- same query string parameters order (param `title` after param `action`)
- with option `Follow HTTP redirection` enabled



![image](https://github.com/ron190/jsql-injection/assets/1971480/e7eac10d-a1e0-43b2-b8ef-33401f91b947)

**Comment by DelvinBa** [comment]
Thanks for the quick answer. 
My scans still detect nothing. Do your scans detect sql injections in bWAPP? 
In the screenshots below you can also see, that I get redirected to the login. Checking the network requests, the tabs "source" and "preview", reveal that I got redirected, right? I think that is a problem... There should be no redirect at all.
I also get this exception "unable to create native thread: possibly out of memory or process/resource limits reached" sometimes.

![Screenshot 2024-05-27 at 20 19 50](https://github.com/ron190/jsql-injection/assets/99075563/7a171c58-b4ae-459f-a401-dec9b2af981a)
![Screenshot 2024-05-27 at 20 24 25](https://github.com/ron190/jsql-injection/assets/99075563/8e46bd61-4c71-4ee1-bb38-33570c8723d6)

**Comment by ron190** [comment]
It's working fine on jSQL [v0.90](https://github.com/ron190/jsql-injection/releases/tag/v0.90) without any option required.

So I suppose that since v0.91 jSQL is aligned with the latest cookie rfc, and I guess bWAPP is not compatible with latest cookie pattern and breaks on new apps (bWAPP is 10 years old). 

Or I introduced a bug... Sad no regression has been detected by Spring integration tests when it passed from v0.90 to v0.91.
It definitely requires to add apache/PHP integration tests to cover similar use cases and prevent broken features (as well as python, .net and node server tests).

Until I or anyone check in more detail you may download and use v0.90, thanks for the report.

![image](https://github.com/ron190/jsql-injection/assets/1971480/73ca25e4-eebf-4ce1-8d7b-2397008149b2)

**Comment by racocvr** [comment]
Hi there,

I have a similar issue. I noticed that the sent cookie value is surounded by quotation marks. I wonder if that's the reason why it doesn't work.

![Screenshot 2024-05-28 104542](https://github.com/ron190/jsql-injection/assets/13097473/a45e5107-cdac-4498-adbb-5839d1604647)

**Comment by ron190** [comment]
Fixed in [v0.96](https://github.com/ron190/jsql-injection/releases/tag/v0.96).
I've added you @DelvinBa as bug reporter into v0.96 release description and added both of you to rolling startup message in jSQL.

Reminding everyone who subscribed to the repo notifications and who are reading this note that you are welcome to contribute, free mention about contributors is usually displayed when the tool starts :)

Thanks again for the report.

![image](https://github.com/ron190/jsql-injection/assets/1971480/549c34a0-064d-4bbf-aa8b-980d240b01d3)
