### ISSUE TITLE
Usability Issues

### ISSUE THREAD

**Issue by DelvinBa** [ron190/jsql-injection#95615]
Hey, here I listed some issues regarding usability.

1. In "Windows > Preferences > Tampering," there are three radio buttons. Once one is selected, there is no way to undo the action without restarting the application.

2. Perhaps I am overlooking something, but clicking "File > Save Tab As" does not seem to trigger any action.

3. The toggle at the top right, which opens the menu bar, is turned off when you start the application, rendering the menu invisible. Initially, I thought there was no menu, but after randomly toggling the switch, the menu appeared. In my opinion, the menu should always be visible, making the toggle unnecessary.

4. I often find myself struggling to understand how to use the tool and what certain functionalities or tabs are for. A more detailed wiki explaining the tool would significantly enhance the user experience. I have noticed recent improvements to the Wiki, so it seems you are already addressing this issue.

**Comment by ron190** [comment]
@DelvinBa Thanks for the detailed feedback, here are some thoughts to reflect on your report until I find improvements to implement:

1. You can use the triple click to uncheck the radio button ; I can add a help tip to make it explicit to the user.

2. Saving a tab is possible only for the dynamic components you open on right:
    - a table from `Database`
    - a page from `Admin page`
    - a file from `Read file`

Whereas the tabs strictly on top of menu bar do not trigger a saving event per se. Also other panels like `Preferences` and `SQL Engine` currently do not trigger a saving event though I may implement something like `Export/Import` if I receive requests from the users.

3. The main goal I followed for Ux/Ui is simplicity, mostly in order to avoid what I see on other security applications, a lot of menu bars and a lot of buttons with an overloaded GUI, whereas what the user wants to do here is usually pretty simple:
```gherkin
Given I'm on the injection app
When I define the target settings and run the process 
Then I get the results displayed
```
Also I aligned the app with other full screen IDE like Intellij and browsers like Firefox and Chrome, with tabs on top and address bar, and without any default menu bar, then user can press <kbd>Alt Left</kbd> or use toggle button on right to show the menu bar.

I'll check to see how to balance between an overloaded GUI and a GUI too light. In addition it can be interesting to know concretely why did you search for the menubar? in order to show a specific setting? like `Preferences`? for other panels?

4. You're right, I recently improved the wiki and also I'm promoting the documentation in the live news showing at startup in the app at bottom. Depending on the feedback and the pull requests opened by contributors it's possible to make the wiki more detailed and exhaustive.

> [!NOTE]
> I'm taking this opportunity to invite all GitHub subscribers who read your thread to contribute to the code and to the wiki.

**Comment by DelvinBa** [comment]
1. Okay, good to know.

2. Yes, an `Export/Import` feature could be useful.

3. + 4. I really understand that and am also a fan of lightweight and simple GUIs. 
I searched for the menu bar to configure test settings in `Preferences`. 
In the cases where I had a problem, you provided solutions that were already implemented, which could fix many of the issues or misunderstandings I had, like the `save as tab` or the three clicks to uncheck a radio button. Therefore, a lot of questions that users have might be resolved by a detailed manual explaining the tool. This could potentially lead to fewer GitHub issues being raised and less work for you in the future.
